version: "3.3"
services:

# Private

  router:
    build: ./netubuntu
    privileged: true
    cap_add:
      - NET_ADMIN
    command: sh -c '/root/router_script.sh'
    networks:
      a_server_network:
        ipv4_address: 10.0.2.254
        # priority: 3
      b_client_network:
        ipv4_address: 10.0.1.254
        # priority: 2
      c_dmz_network:
        ipv4_address: 172.16.123.142

  client:
    build: ./netubuntu
    networks:
      b_client_network:
    #deploy:
    #  replicas: 5

  dhcp_server:
    build: ./dhcp
    networks:
      b_client_network:
  
  #proxy:
  #  build: ./proxy
  #  networks:
  #    b_client_network:
  #      ipv4_address: 10.0.1.253

  load_balancer:
    build: ./nginx/loadbalancer
    volumes:
      - ./nginx/loadbalancer/logs:/var/log/nginx/
    networks:
      a_server_network:
        ipv4_address: 10.0.2.8

  server:
    build: ./nginx/server
    #volumes:
    #  - ./nginx/server/logs:/var/log/nginx/
    networks:
      a_server_network:
    #deploy:
    #  replicas: 4

# DMZ
  edge_router:
    build: ./netubuntu
    privileged: true
    cap_add:
      - NET_ADMIN
    command: sh -c '/root/edge_router_script.sh'
    networks:
      c_dmz_network:
        ipv4_address: 172.16.123.141
      d_public_network:
        ipv4_address: 172.31.255.253
    
  dmz_server:
    build: ./nginx/server
    volumes:
      - ./nginx/server/logs:/var/log/nginx/
    networks:
      c_dmz_network:
        ipv4_address: 172.16.123.132

  dns_server:
    build: ./dns
    privileged: true
    volumes:
      - ./dns/named.conf.options:/etc/bind/named.conf.options
    cap_add:
      - NET_ADMIN
    networks:
      c_dmz_network:
        ipv4_address: 172.16.123.130

  # dns_server_resolver:
  #   build: ./dns_resolver
  #   privileged: true
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     c_dmz_network:
  #       ipv4_address: 172.16.123.131

# Public

  external_client:
    build: ./netubuntu_external_client
    cap_add:
      - NET_ADMIN
    command: sh -c 'ip r a 10.0.0.0/8 via 172.31.255.253 && ./root/sleep.sh'
    dns: 
      - 172.16.123.130
    networks:
      d_public_network:
        ipv4_address: 172.31.255.100
    

networks:

  a_server_network:
    driver: macvlan
    #driver_opts:
    #  parent: ens19.10
    ipam:
      config:
        - subnet: 10.0.2.0/24
        #  gateway: 10.0.2.1
  
  b_client_network:
    driver: macvlan
    #driver_opts:
    #  parent: ens20.10
    ipam:
      config:
        - subnet: 10.0.1.0/24
        #  gateway: 10.0.1.1
        #  ip_range: 10.0.1.0/24

  c_dmz_network:
    driver: macvlan
    #driver_opts:
    #  parent: ens21.10
    ipam:
      config:
        - subnet: 172.16.123.128/28

  d_public_network:
    ipam:
      config:
        - subnet: 172.31.255.0/24
